### ISSUE TITLE
Setup.py giving problems while passing travis tests

### ISSUE THREAD

**Issue by lulivi** [lulivi/hitos-iv#6]
No consigo que pase los test de travis porque el setup.py me está dando problemas.

**Comment by lulivi** [comment]
No idea about how to fix [this travis build error](https://travis-ci.org/lulivi/hitos-iv#L374-L381)

**Comment by seraco** [comment]
I will work on that!

**Comment by lulivi** [comment]
@seraco I guessed that the packages `unittest` and `json` are not needed to include in the `install_requires` because maybe they are inherit in the base python package? Deletinng the install_requires line it pass travis tests... Maybe you can answer my question!
